version: '3'
services:
  admin_panel_django:
    build: ./src
    ports:
      - "0:8000"
    depends_on:
      - admin_panel_postgres
    networks:
      - admin_panel_network
    volumes:
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/
    container_name: admin_panel_django


  admin_panel_postgres:
    image: postgres:16.0
    ports:
      - "0:5432"
    volumes:
      - postgres_data_admin_panel:/var/lib/postgresql/data/
    env_file:
      - src/.env
    container_name: admin_panel_postgres
    networks:
      - admin_panel_network


  admin_panel_nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - admin_panel_django
    ports:
      - "83:80"
    networks:
      - admin_panel_network
    container_name: admin_panel_nginx

volumes:
  postgres_data_admin_panel:
  static_value:
  media_value:

networks:
  admin_panel_network:
    driver: bridge

#networks:
#  admin_panel_network:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.16.58.0/24